name: Prepare to Production

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Prepare dependencies
      run: composer install --no-dev

    - name: Save Changes
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Workflow | Prepare to production"
          git push

